repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust Format
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false
        args: [--all]
        description: Automatically format Rust code before commit
        
      - id: cargo-clippy
        name: Rust Clippy Lints
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        args: [--all-targets, --all-features, --, -D, warnings]
        description: Run Clippy lints and treat warnings as errors
        
      - id: cargo-test
        name: Rust Tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        args: [--all, --all-features]
        description: Run all Rust tests across all packages
        
      - id: cargo-doc
        name: Rust Documentation
        entry: cargo doc
        language: system
        types: [rust]
        pass_filenames: false
        args: [--all, --no-deps, --document-private-items]
        description: Generate documentation for all packages
